//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackLion.QRStore.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItemDetailPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemDetailPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackLion.QRStore.Localization.ItemDetailPageResources", typeof(ItemDetailPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        internal static string Button_Visit {
            get {
                return ResourceManager.GetString("Button_Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t delete this entry due to an error..
        /// </summary>
        internal static string Delete_Item_Error_Modal_Content {
            get {
                return ResourceManager.GetString("Delete_Item_Error_Modal_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Delete_Item_Error_Modal_Ok_Option {
            get {
                return ResourceManager.GetString("Delete_Item_Error_Modal_Ok_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopps!.
        /// </summary>
        internal static string Delete_Item_Error_Modal_Title {
            get {
                return ResourceManager.GetString("Delete_Item_Error_Modal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After pressing &quot;Yes&quot; the entry will be erased and you&apos;ll be unable to recuperate it..
        /// </summary>
        internal static string Delete_Item_Modal_Content {
            get {
                return ResourceManager.GetString("Delete_Item_Modal_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Delete_Item_Modal_No_Option {
            get {
                return ResourceManager.GetString("Delete_Item_Modal_No_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this entry?.
        /// </summary>
        internal static string Delete_Item_Modal_Title {
            get {
                return ResourceManager.GetString("Delete_Item_Modal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Delete_Item_Modal_Yes_Option {
            get {
                return ResourceManager.GetString("Delete_Item_Modal_Yes_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        internal static string Label_URL {
            get {
                return ResourceManager.GetString("Label_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Toolbar_Item_Delete {
            get {
                return ResourceManager.GetString("Toolbar_Item_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Toolbar_Item_Edit {
            get {
                return ResourceManager.GetString("Toolbar_Item_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t open this webpage due to an error..
        /// </summary>
        internal static string Visit_Link_Error_Modal_Content {
            get {
                return ResourceManager.GetString("Visit_Link_Error_Modal_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Visit_Link_Error_Modal_Ok_Option {
            get {
                return ResourceManager.GetString("Visit_Link_Error_Modal_Ok_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopps!.
        /// </summary>
        internal static string Visit_Link_Error_Modal_Title {
            get {
                return ResourceManager.GetString("Visit_Link_Error_Modal_Title", resourceCulture);
            }
        }
    }
}
